# Generated by Mirage (Sat, 19 Jul 2014 00:35:59 GMT).

LIBS   = -pkgs lwt.syntax,mirage-kfreebsd,mirage-console-kfreebsd,mirage-types.lwt
PKGS   = mirage-kfreebsd
SYNTAX = -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal"

FLAGS  = -lflag -linkpkg -lflag -dontlink -lflag unix

BUILD  = OCAMLPARAM="nodynlink=1,nopic=1,fixedpt=16,_" ocamlbuild -classic-display -use-ocamlfind $(LIBS) $(SYNTAX) $(FLAGS)
OPAM   = opam

export PKG_CONFIG_PATH=$(shell opam config var prefix)/lib/pkgconfig

export OPAMVERBOSE=1
export OPAMYES=1

.PHONY: all depend clean build main.native
all: build

depend:
	$(OPAM) install $(PKGS) --verbose

main.native:
	$(BUILD) main.native

main.native.o:
	$(BUILD) main.native.o main.o

_build/module.o: main.native.o
	cc -c module.c -o _build/module.o

_build/main.ko: _build/module.o main.native.o
	ld -nostdlib -r -d -o _build/main.ko _build/main.native.o _build/module.o ~/.opam/mirage-kfreebsd/lib/mirage-kfreebsd/libmir.a
	objcopy --strip-debug _build/main.ko

build: main.native
	ln -nfs _build/main.native mir-console

run: build
	$(SUDO) ./mir-console

clean:
	ocamlbuild -clean
